/**
 * GENERATED by scripts/export-catalog.ts from the frontend's code catalog — do not edit by hand.
 *
 * The first contents of the content catalog (ContentItem). Each entry is inserted once, keyed by
 * type + key, and never overwritten: after that the database (and the admin panel) is in charge.
 */
export interface CatalogSeedEntry {
  type: 'section' | 'class' | 'subject' | 'class_subject' | 'kid_game' | 'game';
  key: string;
  title: string;
  description: string;
  order: number;
  classLevel?: number;
  subject?: string;
  isVisible?: boolean;
  difficulty?: 'easy' | 'medium' | 'hard';
  gameType?: string;
}

export const CATALOG_SEED: readonly CatalogSeedEntry[] = [
  {
    "type": "section",
    "key": "hero",
    "title": "Hero",
    "description": "Headline, introduction and the main call to action.",
    "order": 1
  },
  {
    "type": "section",
    "key": "highlights",
    "title": "Product highlights",
    "description": "Photos, videos, documents, folders and games at a glance.",
    "order": 1.5
  },
  {
    "type": "section",
    "key": "features",
    "title": "Features",
    "description": "What media_tool does, at a glance.",
    "order": 2
  },
  {
    "type": "section",
    "key": "media",
    "title": "Media library",
    "description": "Photos and videos section.",
    "order": 3
  },
  {
    "type": "section",
    "key": "documents",
    "title": "Documents",
    "description": "Documents and in-app previews.",
    "order": 4
  },
  {
    "type": "section",
    "key": "games",
    "title": "Games",
    "description": "The games collection.",
    "order": 5
  },
  {
    "type": "section",
    "key": "kid-games",
    "title": "Kid Games",
    "description": "Learning games for Classes 1–5.",
    "order": 6
  },
  {
    "type": "section",
    "key": "how-it-works",
    "title": "How it works",
    "description": "Three steps from sign-up to your library.",
    "order": 6.4
  },
  {
    "type": "section",
    "key": "security",
    "title": "Security & privacy",
    "description": "How accounts and files are kept private.",
    "order": 6.7
  },
  {
    "type": "section",
    "key": "reviews",
    "title": "Reviews",
    "description": "Approved public reviews.",
    "order": 7
  },
  {
    "type": "section",
    "key": "pricing",
    "title": "Pricing",
    "description": "Free, Pro and Premium plans.",
    "order": 8,
    "isVisible": false
  },
  {
    "type": "section",
    "key": "faq",
    "title": "FAQ",
    "description": "Frequently asked questions.",
    "order": 9
  },
  {
    "type": "section",
    "key": "cta",
    "title": "Final call to action",
    "description": "Closing sign-up prompt.",
    "order": 10
  },
  {
    "type": "section",
    "key": "contact",
    "title": "Contact",
    "description": "The Contact page: support email and help links.",
    "order": 11
  },
  {
    "type": "class",
    "key": "class-1",
    "title": "Class 1",
    "description": "Learn the basics",
    "order": 1,
    "classLevel": 1
  },
  {
    "type": "class",
    "key": "class-2",
    "title": "Class 2",
    "description": "Play and learn",
    "order": 2,
    "classLevel": 2
  },
  {
    "type": "class",
    "key": "class-3",
    "title": "Class 3",
    "description": "Ready for a challenge",
    "order": 3,
    "classLevel": 3
  },
  {
    "type": "class",
    "key": "class-4",
    "title": "Class 4",
    "description": "Solve problems",
    "order": 4,
    "classLevel": 4
  },
  {
    "type": "class",
    "key": "class-5",
    "title": "Class 5",
    "description": "Master the challenge",
    "order": 5,
    "classLevel": 5
  },
  {
    "type": "subject",
    "key": "hindi",
    "title": "Hindi",
    "description": "हिंदी",
    "order": 1
  },
  {
    "type": "subject",
    "key": "english",
    "title": "English",
    "description": "English",
    "order": 2
  },
  {
    "type": "subject",
    "key": "math",
    "title": "Mathematics",
    "description": "Maths",
    "order": 3
  },
  {
    "type": "class_subject",
    "key": "class-1-hindi",
    "title": "Class 1 · Hindi",
    "description": "स्वर, व्यंजन, सरल मात्राएँ और छोटे शब्द",
    "order": 1,
    "classLevel": 1,
    "subject": "hindi"
  },
  {
    "type": "class_subject",
    "key": "class-1-english",
    "title": "Class 1 · English",
    "description": "A–Z, phonics, colours, animals and first words",
    "order": 2,
    "classLevel": 1,
    "subject": "english"
  },
  {
    "type": "class_subject",
    "key": "class-1-math",
    "title": "Class 1 · Mathematics",
    "description": "Counting, numbers, adding and taking away",
    "order": 3,
    "classLevel": 1,
    "subject": "math"
  },
  {
    "type": "class_subject",
    "key": "class-2-hindi",
    "title": "Class 2 · Hindi",
    "description": "मात्राएँ, सरल शब्द और छोटे वाक्य",
    "order": 1,
    "classLevel": 2,
    "subject": "hindi"
  },
  {
    "type": "class_subject",
    "key": "class-2-english",
    "title": "Class 2 · English",
    "description": "Simple sentences, spelling, nouns and verbs",
    "order": 2,
    "classLevel": 2,
    "subject": "english"
  },
  {
    "type": "class_subject",
    "key": "class-2-math",
    "title": "Class 2 · Mathematics",
    "description": "Two-digit sums, tables, place value, time and money",
    "order": 3,
    "classLevel": 2,
    "subject": "math"
  },
  {
    "type": "class_subject",
    "key": "class-3-hindi",
    "title": "Class 3 · Hindi",
    "description": "विलोम, पर्यायवाची, संज्ञा और सर्वनाम",
    "order": 1,
    "classLevel": 3,
    "subject": "hindi"
  },
  {
    "type": "class_subject",
    "key": "class-3-english",
    "title": "Class 3 · English",
    "description": "Grammar basics, adjectives and short passages",
    "order": 2,
    "classLevel": 3,
    "subject": "english"
  },
  {
    "type": "class_subject",
    "key": "class-3-math",
    "title": "Class 3 · Mathematics",
    "description": "Multiplication, division, fractions and measurement",
    "order": 3,
    "classLevel": 3,
    "subject": "math"
  },
  {
    "type": "class_subject",
    "key": "class-4-hindi",
    "title": "Class 4 · Hindi",
    "description": "विशेषण, क्रिया, वाक्य सुधार और पठन",
    "order": 1,
    "classLevel": 4,
    "subject": "hindi"
  },
  {
    "type": "class_subject",
    "key": "class-4-english",
    "title": "Class 4 · English",
    "description": "Tenses, parts of speech and comprehension",
    "order": 2,
    "classLevel": 4,
    "subject": "english"
  },
  {
    "type": "class_subject",
    "key": "class-4-math",
    "title": "Class 4 · Mathematics",
    "description": "Large numbers, fractions, decimals and word problems",
    "order": 3,
    "classLevel": 4,
    "subject": "math"
  },
  {
    "type": "class_subject",
    "key": "class-5-hindi",
    "title": "Class 5 · Hindi",
    "description": "काल, वाक्य संरचना, मुहावरे और शुद्ध वाक्य",
    "order": 1,
    "classLevel": 5,
    "subject": "hindi"
  },
  {
    "type": "class_subject",
    "key": "class-5-english",
    "title": "Class 5 · English",
    "description": "Tenses, agreement and reading comprehension",
    "order": 2,
    "classLevel": 5,
    "subject": "english"
  },
  {
    "type": "class_subject",
    "key": "class-5-math",
    "title": "Class 5 · Mathematics",
    "description": "Fractions, decimals, percentages and reasoning",
    "order": 3,
    "classLevel": 5,
    "subject": "math"
  },
  {
    "type": "kid_game",
    "key": "c1-hindi-varn-pehchan",
    "title": "स्वर-व्यंजन छाँटो",
    "description": "स्वर और व्यंजन को अलग-अलग डिब्बे में रखो।",
    "order": 1,
    "classLevel": 1,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c1-hindi-matra-milao",
    "title": "मात्रा पहचान",
    "description": "ा, ि और ी की मात्रा वाले अक्षर मिलाओ।",
    "order": 2,
    "classLevel": 1,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c1-hindi-shabd-banao",
    "title": "शब्द बनाओ",
    "description": "अक्षर जोड़कर कमल, घर जैसे छोटे शब्द बनाओ।",
    "order": 3,
    "classLevel": 1,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "word-builder"
  },
  {
    "type": "kid_game",
    "key": "c1-hindi-chitra-shabd",
    "title": "चित्र से शब्द",
    "description": "चित्र देखो और उसका सही नाम चुनो।",
    "order": 4,
    "classLevel": 1,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "image-choice"
  },
  {
    "type": "kid_game",
    "key": "c1-hindi-sahi-shabd",
    "title": "अक्षर पहचान",
    "description": "सही अक्षर और सही शब्द चुनो।",
    "order": 5,
    "classLevel": 1,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c1-hindi-akshar-kram",
    "title": "अक्षर क्रम",
    "description": "स्वर और व्यंजन को वर्णमाला के क्रम में लगाओ।",
    "order": 6,
    "classLevel": 1,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c1-hindi-shabd-milan",
    "title": "अक्षर मिलाओ",
    "description": "पत्ते पलटो और चित्र-शब्द की जोड़ी ढूँढो।",
    "order": 7,
    "classLevel": 1,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "memory"
  },
  {
    "type": "kid_game",
    "key": "c1-hindi-rikt-sthan",
    "title": "छूटा अक्षर भरो",
    "description": "शब्द में छूटा हुआ अक्षर भरो।",
    "order": 8,
    "classLevel": 1,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "fill-blank"
  },
  {
    "type": "kid_game",
    "key": "c1-hindi-vakya-poora",
    "title": "छोटे वाक्य",
    "description": "छोटे-छोटे वाक्य पढ़ो और पूरे करो।",
    "order": 9,
    "classLevel": 1,
    "subject": "hindi",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c1-hindi-hindi-quiz",
    "title": "वर्णमाला क्विज़",
    "description": "स्वर, व्यंजन, मात्रा और शब्दों का मज़ेदार क्विज़।",
    "order": 10,
    "classLevel": 1,
    "subject": "hindi",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c1-english-alphabet-adventure",
    "title": "Alphabet Adventure",
    "description": "Put the letters A to Z in order.",
    "order": 1,
    "classLevel": 1,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c1-english-word-match",
    "title": "Letter Match",
    "description": "Match big letters, small letters and first sounds.",
    "order": 2,
    "classLevel": 1,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c1-english-picture-word-match",
    "title": "Picture Word Match",
    "description": "Flip cards to pair pictures with their words.",
    "order": 3,
    "classLevel": 1,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "memory"
  },
  {
    "type": "kid_game",
    "key": "c1-english-spell-it",
    "title": "Spell It",
    "description": "Look at the picture and pick the right spelling.",
    "order": 4,
    "classLevel": 1,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "image-choice"
  },
  {
    "type": "kid_game",
    "key": "c1-english-missing-letter",
    "title": "Missing Letter",
    "description": "Find the letter missing from the word.",
    "order": 5,
    "classLevel": 1,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "fill-blank"
  },
  {
    "type": "kid_game",
    "key": "c1-english-sentence-builder",
    "title": "Simple Sentence",
    "description": "Put three or four words together to make a sentence.",
    "order": 6,
    "classLevel": 1,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "word-builder"
  },
  {
    "type": "kid_game",
    "key": "c1-english-grammar-quest",
    "title": "Sorting Fun",
    "description": "Sort animals, colours, fruits and letters.",
    "order": 7,
    "classLevel": 1,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c1-english-vocabulary-challenge",
    "title": "Beginning Sound",
    "description": "First sounds, colours, opposites and rhymes.",
    "order": 8,
    "classLevel": 1,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c1-english-reading-challenge",
    "title": "Read and Find",
    "description": "Read a tiny sentence and answer the question.",
    "order": 9,
    "classLevel": 1,
    "subject": "english",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c1-english-english-quiz",
    "title": "ABC Quiz",
    "description": "A mixed quiz on letters, sounds and first words.",
    "order": 10,
    "classLevel": 1,
    "subject": "english",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c1-math-number-runner",
    "title": "Number Order",
    "description": "Line up numbers up to 50, smallest first.",
    "order": 1,
    "classLevel": 1,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c1-math-counting-challenge",
    "title": "Count the Objects",
    "description": "Count the pictures and type how many.",
    "order": 2,
    "classLevel": 1,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c1-math-addition-adventure",
    "title": "Addition Fun",
    "description": "Add numbers within 20.",
    "order": 3,
    "classLevel": 1,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c1-math-subtraction-challenge",
    "title": "Subtraction Fun",
    "description": "Take away within 20 and type what is left.",
    "order": 4,
    "classLevel": 1,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c1-math-multiplication-quest",
    "title": "Equal Groups",
    "description": "Add the same number again and again.",
    "order": 5,
    "classLevel": 1,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c1-math-division-challenge",
    "title": "Share It Out",
    "description": "Share equally and match each to how many it gets.",
    "order": 6,
    "classLevel": 1,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c1-math-number-comparison",
    "title": "Bigger or Smaller",
    "description": "Sort numbers into bigger and smaller.",
    "order": 7,
    "classLevel": 1,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c1-math-missing-number",
    "title": "Missing Number",
    "description": "Find the number that is missing.",
    "order": 8,
    "classLevel": 1,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c1-math-pattern-puzzle",
    "title": "Simple Patterns",
    "description": "Spot the colour, shape or number pattern.",
    "order": 9,
    "classLevel": 1,
    "subject": "math",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c1-math-math-quiz",
    "title": "Shape and Money Quiz",
    "description": "Shapes, time, money and sums in one quiz.",
    "order": 10,
    "classLevel": 1,
    "subject": "math",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c2-hindi-varn-pehchan",
    "title": "एक-अनेक और लिंग",
    "description": "शब्दों को मात्रा, वचन और लिंग के समूह में रखो।",
    "order": 1,
    "classLevel": 2,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c2-hindi-matra-milao",
    "title": "मात्रा अभ्यास",
    "description": "सभी मात्राओं वाले अक्षर और शब्द मिलाओ।",
    "order": 2,
    "classLevel": 2,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c2-hindi-shabd-banao",
    "title": "शब्द पहेली",
    "description": "अक्षर जोड़कर मात्रा वाले शब्द बनाओ।",
    "order": 3,
    "classLevel": 2,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "word-builder"
  },
  {
    "type": "kid_game",
    "key": "c2-hindi-chitra-shabd",
    "title": "चित्र से वर्तनी",
    "description": "चित्र देखो और सही वर्तनी वाला नाम चुनो।",
    "order": 4,
    "classLevel": 2,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "image-choice"
  },
  {
    "type": "kid_game",
    "key": "c2-hindi-sahi-shabd",
    "title": "सही शब्द चुनो",
    "description": "सही वर्तनी, सही वचन और सही लिंग पहचानो।",
    "order": 5,
    "classLevel": 2,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c2-hindi-akshar-kram",
    "title": "शब्द क्रम",
    "description": "दिनों, बारहखड़ी और वाक्य के शब्दों का क्रम लगाओ।",
    "order": 6,
    "classLevel": 2,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c2-hindi-shabd-milan",
    "title": "नर-मादा जोड़ी",
    "description": "पत्ते पलटो: एक-अनेक और नर-मादा की जोड़ियाँ।",
    "order": 7,
    "classLevel": 2,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "memory"
  },
  {
    "type": "kid_game",
    "key": "c2-hindi-rikt-sthan",
    "title": "शब्द पहचान",
    "description": "वाक्य में सही शब्द भरो।",
    "order": 8,
    "classLevel": 2,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "fill-blank"
  },
  {
    "type": "kid_game",
    "key": "c2-hindi-vakya-poora",
    "title": "वाक्य पूरा करो",
    "description": "पढ़ो, समझो और वाक्य पूरा करो।",
    "order": 9,
    "classLevel": 2,
    "subject": "hindi",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c2-hindi-hindi-quiz",
    "title": "मात्रा क्विज़",
    "description": "मात्राएँ, शब्द और वाक्य — सब का क्विज़।",
    "order": 10,
    "classLevel": 2,
    "subject": "hindi",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c2-english-alphabet-adventure",
    "title": "Days and Months",
    "description": "Put words, days and months in order.",
    "order": 1,
    "classLevel": 2,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c2-english-word-match",
    "title": "Opposite Words",
    "description": "Match opposites, plurals and pronouns.",
    "order": 2,
    "classLevel": 2,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c2-english-picture-word-match",
    "title": "Picture Vocabulary",
    "description": "Flip cards to pair pictures with their words.",
    "order": 3,
    "classLevel": 2,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "memory"
  },
  {
    "type": "kid_game",
    "key": "c2-english-spell-it",
    "title": "Spell Challenge",
    "description": "Pick the right spelling of everyday words.",
    "order": 4,
    "classLevel": 2,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "image-choice"
  },
  {
    "type": "kid_game",
    "key": "c2-english-missing-letter",
    "title": "Word Scramble",
    "description": "Find the letters missing from longer words.",
    "order": 5,
    "classLevel": 2,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "fill-blank"
  },
  {
    "type": "kid_game",
    "key": "c2-english-sentence-builder",
    "title": "Sentence Builder",
    "description": "Build sentences with he, she, it and they.",
    "order": 6,
    "classLevel": 2,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "word-builder"
  },
  {
    "type": "kid_game",
    "key": "c2-english-grammar-quest",
    "title": "Noun and Verb Hunt",
    "description": "Sort naming words and doing words.",
    "order": 7,
    "classLevel": 2,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c2-english-vocabulary-challenge",
    "title": "Plural Match",
    "description": "Opposites, same meanings and one or many.",
    "order": 8,
    "classLevel": 2,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c2-english-reading-challenge",
    "title": "Story Time",
    "description": "Read short sentences and answer questions.",
    "order": 9,
    "classLevel": 2,
    "subject": "english",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c2-english-english-quiz",
    "title": "Word Power Quiz",
    "description": "Nouns, verbs, pronouns and spelling in one quiz.",
    "order": 10,
    "classLevel": 2,
    "subject": "english",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c2-math-number-runner",
    "title": "Number Adventure",
    "description": "Put two- and three-digit numbers in order.",
    "order": 1,
    "classLevel": 2,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c2-math-counting-challenge",
    "title": "Place Value",
    "description": "Skip count and find tens and ones.",
    "order": 2,
    "classLevel": 2,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c2-math-addition-adventure",
    "title": "Addition Challenge",
    "description": "Add two-digit numbers.",
    "order": 3,
    "classLevel": 2,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c2-math-subtraction-challenge",
    "title": "Subtraction Race",
    "description": "Subtract two-digit numbers.",
    "order": 4,
    "classLevel": 2,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c2-math-multiplication-quest",
    "title": "Multiplication Intro",
    "description": "Tables of 2, 3, 4 and 5.",
    "order": 5,
    "classLevel": 2,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c2-math-division-challenge",
    "title": "Division Intro",
    "description": "Share equally and make groups.",
    "order": 6,
    "classLevel": 2,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c2-math-number-comparison",
    "title": "Number Comparison",
    "description": "Compare numbers; sort even, odd, 2D and 3D.",
    "order": 7,
    "classLevel": 2,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c2-math-missing-number",
    "title": "Number Detective",
    "description": "Find missing numbers in sums and tables.",
    "order": 8,
    "classLevel": 2,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c2-math-pattern-puzzle",
    "title": "Patterns",
    "description": "Shape patterns and skip-counting patterns.",
    "order": 9,
    "classLevel": 2,
    "subject": "math",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c2-math-math-quiz",
    "title": "Time and Money Match",
    "description": "Clocks, rupees, shapes and place value.",
    "order": 10,
    "classLevel": 2,
    "subject": "math",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c3-hindi-varn-pehchan",
    "title": "संज्ञा-सर्वनाम छाँटो",
    "description": "संज्ञा, सर्वनाम, विलोम और पर्यायवाची अलग करो।",
    "order": 1,
    "classLevel": 3,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c3-hindi-matra-milao",
    "title": "विलोम शब्द मिलाओ",
    "description": "शब्दों को उनके विलोम और पर्यायवाची से मिलाओ।",
    "order": 2,
    "classLevel": 3,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c3-hindi-shabd-banao",
    "title": "वाक्य बनाओ",
    "description": "बड़े शब्द और सरल वाक्य बनाओ।",
    "order": 3,
    "classLevel": 3,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "word-builder"
  },
  {
    "type": "kid_game",
    "key": "c3-hindi-chitra-shabd",
    "title": "चित्र पर्यायवाची",
    "description": "चित्र देखो और उसका पर्यायवाची चुनो।",
    "order": 4,
    "classLevel": 3,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "image-choice"
  },
  {
    "type": "kid_game",
    "key": "c3-hindi-sahi-shabd",
    "title": "व्याकरण पहचान",
    "description": "विलोम, पर्यायवाची, संज्ञा और सर्वनाम पहचानो।",
    "order": 5,
    "classLevel": 3,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c3-hindi-akshar-kram",
    "title": "शब्दकोश क्रम",
    "description": "शब्दों, महीनों और कहानी को सही क्रम में लगाओ।",
    "order": 6,
    "classLevel": 3,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c3-hindi-shabd-milan",
    "title": "पर्यायवाची जोड़ी",
    "description": "पत्ते पलटो: विलोम, पर्यायवाची और वचन की जोड़ियाँ।",
    "order": 7,
    "classLevel": 3,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "memory"
  },
  {
    "type": "kid_game",
    "key": "c3-hindi-rikt-sthan",
    "title": "सही संज्ञा भरो",
    "description": "वाक्य में सही संज्ञा और सर्वनाम भरो।",
    "order": 8,
    "classLevel": 3,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "fill-blank"
  },
  {
    "type": "kid_game",
    "key": "c3-hindi-vakya-poora",
    "title": "पढ़ो और समझो",
    "description": "छोटे अनुच्छेद पढ़ो और प्रश्नों के उत्तर दो।",
    "order": 9,
    "classLevel": 3,
    "subject": "hindi",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c3-hindi-hindi-quiz",
    "title": "व्याकरण क्विज़",
    "description": "विलोम, पर्यायवाची, संज्ञा, सर्वनाम और वचन का क्विज़।",
    "order": 10,
    "classLevel": 3,
    "subject": "hindi",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c3-english-alphabet-adventure",
    "title": "Dictionary Detective",
    "description": "Order words by their second letter, and put stories in order.",
    "order": 1,
    "classLevel": 3,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c3-english-word-match",
    "title": "Synonym Match",
    "description": "Match opposites, same meanings, plurals and genders.",
    "order": 2,
    "classLevel": 3,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c3-english-picture-word-match",
    "title": "Nature Words",
    "description": "Flip cards: animals, insects, weather and tools.",
    "order": 3,
    "classLevel": 3,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "memory"
  },
  {
    "type": "kid_game",
    "key": "c3-english-spell-it",
    "title": "Tricky Spellings",
    "description": "Pick the right spelling of longer words.",
    "order": 4,
    "classLevel": 3,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "image-choice"
  },
  {
    "type": "kid_game",
    "key": "c3-english-missing-letter",
    "title": "Missing Word",
    "description": "Fill in a, an, the, is, am, are and describing words.",
    "order": 5,
    "classLevel": 3,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "fill-blank"
  },
  {
    "type": "kid_game",
    "key": "c3-english-sentence-builder",
    "title": "Sentence Maker",
    "description": "Build sentences of five or six words.",
    "order": 6,
    "classLevel": 3,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "word-builder"
  },
  {
    "type": "kid_game",
    "key": "c3-english-grammar-quest",
    "title": "Adjective Quest",
    "description": "Sort nouns, verbs and adjectives.",
    "order": 7,
    "classLevel": 3,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c3-english-vocabulary-challenge",
    "title": "Word Wizard",
    "description": "Opposites, synonyms, genders and group words.",
    "order": 8,
    "classLevel": 3,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c3-english-reading-challenge",
    "title": "Reading Detective",
    "description": "Read short passages and find the answers.",
    "order": 9,
    "classLevel": 3,
    "subject": "english",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c3-english-english-quiz",
    "title": "Grammar Quiz",
    "description": "A mixed quiz on grammar basics and vocabulary.",
    "order": 10,
    "classLevel": 3,
    "subject": "english",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c3-math-number-runner",
    "title": "Fraction Line-up",
    "description": "Order 3-digit numbers, fractions and lengths.",
    "order": 1,
    "classLevel": 3,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c3-math-counting-challenge",
    "title": "Place Value Puzzle",
    "description": "Place value, skip counting, faces and edges.",
    "order": 2,
    "classLevel": 3,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c3-math-addition-adventure",
    "title": "Addition",
    "description": "Add three-digit numbers, with carrying.",
    "order": 3,
    "classLevel": 3,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c3-math-subtraction-challenge",
    "title": "Subtraction",
    "description": "Subtract three-digit numbers, with borrowing.",
    "order": 4,
    "classLevel": 3,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c3-math-multiplication-quest",
    "title": "Multiplication",
    "description": "Tables up to 10 and 2-digit × 1-digit.",
    "order": 5,
    "classLevel": 3,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c3-math-division-challenge",
    "title": "Division",
    "description": "Division facts, remainders and fractions.",
    "order": 6,
    "classLevel": 3,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c3-math-number-comparison",
    "title": "Fractions",
    "description": "Compare numbers, fractions and lengths.",
    "order": 7,
    "classLevel": 3,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c3-math-missing-number",
    "title": "Number Puzzles",
    "description": "Find missing numbers in tables and fractions.",
    "order": 8,
    "classLevel": 3,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c3-math-pattern-puzzle",
    "title": "Number Patterns",
    "description": "Adding, doubling and growing patterns.",
    "order": 9,
    "classLevel": 3,
    "subject": "math",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c3-math-math-quiz",
    "title": "Time, Money and Geometry",
    "description": "Measurement, time, money and shapes.",
    "order": 10,
    "classLevel": 3,
    "subject": "math",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c4-hindi-varn-pehchan",
    "title": "शब्द-भेद छाँटो",
    "description": "संज्ञा, विशेषण और क्रिया को सही समूह में रखो।",
    "order": 1,
    "classLevel": 4,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c4-hindi-matra-milao",
    "title": "विशेषण बनाओ",
    "description": "संज्ञा से बने विशेषण, भाववाचक और विलोम मिलाओ।",
    "order": 2,
    "classLevel": 4,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c4-hindi-shabd-banao",
    "title": "वाक्य रचना",
    "description": "शब्द जोड़कर सही वाक्य बनाओ।",
    "order": 3,
    "classLevel": 4,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "word-builder"
  },
  {
    "type": "kid_game",
    "key": "c4-hindi-chitra-shabd",
    "title": "चित्र से क्रिया",
    "description": "चित्र देखो: कौन-सी क्रिया या विशेषण है?",
    "order": 4,
    "classLevel": 4,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "image-choice"
  },
  {
    "type": "kid_game",
    "key": "c4-hindi-sahi-shabd",
    "title": "वाक्य सुधार",
    "description": "शुद्ध वर्तनी और शुद्ध वाक्य चुनो।",
    "order": 5,
    "classLevel": 4,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c4-hindi-akshar-kram",
    "title": "घटनाओं का क्रम",
    "description": "शब्दकोश, वाक्य और घटनाओं का सही क्रम लगाओ।",
    "order": 6,
    "classLevel": 4,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c4-hindi-shabd-milan",
    "title": "एक शब्द जोड़ी",
    "description": "पत्ते पलटो: अनेक शब्दों के लिए एक शब्द ढूँढो।",
    "order": 7,
    "classLevel": 4,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "memory"
  },
  {
    "type": "kid_game",
    "key": "c4-hindi-rikt-sthan",
    "title": "क्रिया-विशेषण भरो",
    "description": "वाक्य में सही क्रिया, विशेषण और सर्वनाम भरो।",
    "order": 8,
    "classLevel": 4,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "fill-blank"
  },
  {
    "type": "kid_game",
    "key": "c4-hindi-vakya-poora",
    "title": "अनुच्छेद प्रश्न",
    "description": "अनुच्छेद पढ़ो और समझकर उत्तर दो।",
    "order": 9,
    "classLevel": 4,
    "subject": "hindi",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c4-hindi-hindi-quiz",
    "title": "व्याकरण चैंपियन",
    "description": "शब्द-भेद, वचन, लिंग, विलोम और शुद्ध वाक्य।",
    "order": 10,
    "classLevel": 4,
    "subject": "hindi",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c4-english-alphabet-adventure",
    "title": "Dictionary Skills",
    "description": "Order words that begin the same way.",
    "order": 1,
    "classLevel": 4,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c4-english-word-match",
    "title": "Tense Match",
    "description": "Match verbs to their past tense, prefixes and homophones.",
    "order": 2,
    "classLevel": 4,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c4-english-picture-word-match",
    "title": "Big Word Memory",
    "description": "Flip cards: harder words and their meanings.",
    "order": 3,
    "classLevel": 4,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "memory"
  },
  {
    "type": "kid_game",
    "key": "c4-english-spell-it",
    "title": "Spelling Bee",
    "description": "Choose the right spelling of tricky words.",
    "order": 4,
    "classLevel": 4,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "image-choice"
  },
  {
    "type": "kid_game",
    "key": "c4-english-missing-letter",
    "title": "Preposition Puzzle",
    "description": "Fill in tenses, prepositions and comparing words.",
    "order": 5,
    "classLevel": 4,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "fill-blank"
  },
  {
    "type": "kid_game",
    "key": "c4-english-sentence-builder",
    "title": "Time Travel Sentences",
    "description": "Build sentences in the past, present and future.",
    "order": 6,
    "classLevel": 4,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "word-builder"
  },
  {
    "type": "kid_game",
    "key": "c4-english-grammar-quest",
    "title": "Parts of Speech",
    "description": "Sort words by tense and part of speech.",
    "order": 7,
    "classLevel": 4,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c4-english-vocabulary-challenge",
    "title": "Synonyms and Antonyms",
    "description": "Meanings, prefixes and similes.",
    "order": 8,
    "classLevel": 4,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c4-english-reading-challenge",
    "title": "Comprehension Quest",
    "description": "Read a passage and find facts and meanings.",
    "order": 9,
    "classLevel": 4,
    "subject": "english",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c4-english-english-quiz",
    "title": "Tense Challenge",
    "description": "Tenses, parts of speech and vocabulary.",
    "order": 10,
    "classLevel": 4,
    "subject": "english",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c4-math-number-runner",
    "title": "Large Numbers",
    "description": "Order 4-digit numbers, fractions and decimals.",
    "order": 1,
    "classLevel": 4,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c4-math-counting-challenge",
    "title": "Rounding Off",
    "description": "Place value, rounding and large numbers.",
    "order": 2,
    "classLevel": 4,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c4-math-addition-adventure",
    "title": "Big Number Sums",
    "description": "Add 4-digit numbers, decimals and fractions.",
    "order": 3,
    "classLevel": 4,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c4-math-subtraction-challenge",
    "title": "Decimal Difference",
    "description": "Subtract 4-digit numbers, decimals and fractions.",
    "order": 4,
    "classLevel": 4,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c4-math-multiplication-quest",
    "title": "Multiplication",
    "description": "Multiply bigger numbers.",
    "order": 5,
    "classLevel": 4,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c4-math-division-challenge",
    "title": "Division and Decimals",
    "description": "Long division, equivalent fractions and decimals.",
    "order": 6,
    "classLevel": 4,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c4-math-number-comparison",
    "title": "Geometry Sort",
    "description": "Compare numbers, fractions and angles.",
    "order": 7,
    "classLevel": 4,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c4-math-missing-number",
    "title": "Number Mystery",
    "description": "Missing numbers in ×, ÷, fractions and decimals.",
    "order": 8,
    "classLevel": 4,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c4-math-pattern-puzzle",
    "title": "Patterns",
    "description": "Number and decimal patterns and growing rules.",
    "order": 9,
    "classLevel": 4,
    "subject": "math",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c4-math-math-quiz",
    "title": "Measurement and Time",
    "description": "Length, weight, time, angles and money.",
    "order": 10,
    "classLevel": 4,
    "subject": "math",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c5-hindi-varn-pehchan",
    "title": "काल छाँटो",
    "description": "वाक्यों को भूत, वर्तमान और भविष्य काल में रखो।",
    "order": 1,
    "classLevel": 5,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c5-hindi-matra-milao",
    "title": "मुहावरे मिलाओ",
    "description": "हर मुहावरे को उसके सही अर्थ से मिलाओ।",
    "order": 2,
    "classLevel": 5,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c5-hindi-shabd-banao",
    "title": "काल से वाक्य",
    "description": "काल के अनुसार वाक्य और कठिन शब्द बनाओ।",
    "order": 3,
    "classLevel": 5,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "word-builder"
  },
  {
    "type": "kid_game",
    "key": "c5-hindi-chitra-shabd",
    "title": "चित्र मुहावरे",
    "description": "चित्र देखो: पर्यायवाची या मुहावरा पहचानो।",
    "order": 4,
    "classLevel": 5,
    "subject": "hindi",
    "difficulty": "easy",
    "gameType": "image-choice"
  },
  {
    "type": "kid_game",
    "key": "c5-hindi-sahi-shabd",
    "title": "शुद्ध वाक्य चुनो",
    "description": "शुद्ध वर्तनी, शुद्ध वाक्य, काल और मुहावरे।",
    "order": 5,
    "classLevel": 5,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c5-hindi-akshar-kram",
    "title": "वाक्य संरचना",
    "description": "शब्दों और घटनाओं को सही क्रम में लगाओ।",
    "order": 6,
    "classLevel": 5,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c5-hindi-shabd-milan",
    "title": "तत्सम-तद्भव जोड़ी",
    "description": "पत्ते पलटो: मुहावरे, पर्यायवाची और तत्सम-तद्भव।",
    "order": 7,
    "classLevel": 5,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "memory"
  },
  {
    "type": "kid_game",
    "key": "c5-hindi-rikt-sthan",
    "title": "सही शब्द-रूप भरो",
    "description": "काल और मुहावरे के अनुसार सही शब्द भरो।",
    "order": 8,
    "classLevel": 5,
    "subject": "hindi",
    "difficulty": "medium",
    "gameType": "fill-blank"
  },
  {
    "type": "kid_game",
    "key": "c5-hindi-vakya-poora",
    "title": "अनुच्छेद चुनौती",
    "description": "लंबे अनुच्छेद पढ़ो, सोचो और उत्तर दो।",
    "order": 9,
    "classLevel": 5,
    "subject": "hindi",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c5-hindi-hindi-quiz",
    "title": "हिंदी महाक्विज़",
    "description": "काल, मुहावरे, पर्यायवाची, विलोम और शुद्ध वाक्य।",
    "order": 10,
    "classLevel": 5,
    "subject": "hindi",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c5-english-alphabet-adventure",
    "title": "Event Order",
    "description": "Order long words and the events of a story.",
    "order": 1,
    "classLevel": 5,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c5-english-word-match",
    "title": "Idiom Match",
    "description": "Past participles, idioms and one-word answers.",
    "order": 2,
    "classLevel": 5,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c5-english-picture-word-match",
    "title": "Science Words",
    "description": "Flip cards: science words, synonyms and homophones.",
    "order": 3,
    "classLevel": 5,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "memory"
  },
  {
    "type": "kid_game",
    "key": "c5-english-spell-it",
    "title": "Spelling Master",
    "description": "Choose the right spelling of long, difficult words.",
    "order": 4,
    "classLevel": 5,
    "subject": "english",
    "difficulty": "easy",
    "gameType": "image-choice"
  },
  {
    "type": "kid_game",
    "key": "c5-english-missing-letter",
    "title": "Tense Fix",
    "description": "Continuous and perfect tenses, agreement and prepositions.",
    "order": 5,
    "classLevel": 5,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "fill-blank"
  },
  {
    "type": "kid_game",
    "key": "c5-english-sentence-builder",
    "title": "Sentence Correction",
    "description": "Build long sentences with the right tense and agreement.",
    "order": 6,
    "classLevel": 5,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "word-builder"
  },
  {
    "type": "kid_game",
    "key": "c5-english-grammar-quest",
    "title": "Agreement Quest",
    "description": "Countable nouns, subject–verb agreement and tense forms.",
    "order": 7,
    "classLevel": 5,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c5-english-vocabulary-challenge",
    "title": "Vocabulary Master",
    "description": "Synonyms, antonyms, idioms and word forms.",
    "order": 8,
    "classLevel": 5,
    "subject": "english",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c5-english-reading-challenge",
    "title": "Deep Reading",
    "description": "Read longer passages and think about them.",
    "order": 9,
    "classLevel": 5,
    "subject": "english",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c5-english-english-quiz",
    "title": "English Champion",
    "description": "Tenses, agreement and vocabulary in one big quiz.",
    "order": 10,
    "classLevel": 5,
    "subject": "english",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "kid_game",
    "key": "c5-math-number-runner",
    "title": "Percentage Line-up",
    "description": "Order large numbers, decimals and percentages.",
    "order": 1,
    "classLevel": 5,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "ordering"
  },
  {
    "type": "kid_game",
    "key": "c5-math-counting-challenge",
    "title": "Lakhs and Crores",
    "description": "Indian place value, rounding and counting cubes.",
    "order": 2,
    "classLevel": 5,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c5-math-addition-adventure",
    "title": "Fractions and Decimals",
    "description": "Add large numbers, decimals and unlike fractions.",
    "order": 3,
    "classLevel": 5,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c5-math-subtraction-challenge",
    "title": "Decimal Subtraction",
    "description": "Subtract large numbers, decimals and fractions.",
    "order": 4,
    "classLevel": 5,
    "subject": "math",
    "difficulty": "easy",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c5-math-multiplication-quest",
    "title": "Factors and Multiples",
    "description": "Large multiplication, decimals and percentages.",
    "order": 5,
    "classLevel": 5,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c5-math-division-challenge",
    "title": "Percentage Basics",
    "description": "Match fractions, decimals and percentages.",
    "order": 6,
    "classLevel": 5,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "matching"
  },
  {
    "type": "kid_game",
    "key": "c5-math-number-comparison",
    "title": "Prime Sort",
    "description": "Compare fractions and percents; sort primes.",
    "order": 7,
    "classLevel": 5,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "drag-drop"
  },
  {
    "type": "kid_game",
    "key": "c5-math-missing-number",
    "title": "Average and Missing Values",
    "description": "Fractions, decimals, percentages and averages.",
    "order": 8,
    "classLevel": 5,
    "subject": "math",
    "difficulty": "medium",
    "gameType": "number-pad"
  },
  {
    "type": "kid_game",
    "key": "c5-math-pattern-puzzle",
    "title": "Logical Maths",
    "description": "Number patterns and reasoning puzzles.",
    "order": 9,
    "classLevel": 5,
    "subject": "math",
    "difficulty": "hard",
    "gameType": "multiple-choice"
  },
  {
    "type": "kid_game",
    "key": "c5-math-math-quiz",
    "title": "Word Problem Master",
    "description": "Area, perimeter, volume, time and money.",
    "order": 10,
    "classLevel": 5,
    "subject": "math",
    "difficulty": "hard",
    "gameType": "timed-quiz"
  },
  {
    "type": "game",
    "key": "water-race",
    "title": "Water Race",
    "description": "Fill your tank before the other team does",
    "order": 1
  },
  {
    "type": "game",
    "key": "memory-match",
    "title": "Memory Match",
    "description": "Flip cards and find every pair",
    "order": 2
  },
  {
    "type": "game",
    "key": "reaction-test",
    "title": "Reaction Test",
    "description": "Three ways to test your reflexes",
    "order": 3
  },
  {
    "type": "game",
    "key": "target-click",
    "title": "Target Click",
    "description": "Arcade aim challenge with combos",
    "order": 4
  },
  {
    "type": "game",
    "key": "number-puzzle",
    "title": "Number Puzzle",
    "description": "Slide the tiles into order",
    "order": 5
  },
  {
    "type": "game",
    "key": "snake",
    "title": "Snake",
    "description": "Eat, grow and outlast the walls",
    "order": 6
  },
  {
    "type": "game",
    "key": "ludo",
    "title": "Ludo",
    "description": "Classic Multiplayer Board Game · 2–4 Players",
    "order": 7
  }
];
