/**
 * Writes backend/src/content/catalogSeed.ts from the catalog the frontend code defines: website
 * sections, Kid Games classes, subjects and games, and the arcade games.
 *
 * The seed is only the *starting point* of the database catalog (inserted once per entry, never
 * overwriting what an administrator changed). Re-run this after adding a game or class in code, so
 * the new entry appears in the admin panel:
 *
 *   npx tsx scripts/export-catalog.ts
 *
 * frontend/tests/catalogSeed.test.ts fails if the seed and the code catalog drift apart.
 */
import fs from 'node:fs';
import path from 'node:path';
import { buildCatalogSeed } from '../frontend/lib/content/catalogManifest';

const out = path.resolve(__dirname, '../backend/src/content/catalogSeed.ts');
const entries = buildCatalogSeed();

const body = `/**
 * GENERATED by scripts/export-catalog.ts from the frontend's code catalog — do not edit by hand.
 *
 * The first contents of the content catalog (ContentItem). Each entry is inserted once, keyed by
 * type + key, and never overwritten: after that the database (and the admin panel) is in charge.
 */
export interface CatalogSeedEntry {
  type: 'section' | 'class' | 'subject' | 'class_subject' | 'kid_game' | 'game';
  key: string;
  title: string;
  description: string;
  order: number;
  classLevel?: number;
  subject?: string;
  isVisible?: boolean;
  difficulty?: 'easy' | 'medium' | 'hard';
  gameType?: string;
}

export const CATALOG_SEED: readonly CatalogSeedEntry[] = ${JSON.stringify(entries, null, 2)};
`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, body);
console.log(`Wrote ${entries.length} catalog entries to ${path.relative(process.cwd(), out)}`);
